version: '3.8'

services:
  nginx-rtmp-olegueresteo:
    image: alfg/nginx-rtmp
    container_name: streaming-video-olegueresteo
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/www/static
      - ./hls:/opt/data/hls
    restart: unless-stopped